#steps
#clone  
# create env
# build npm i
# deploy to server
# create back service file
# add nginx conf
# start service 

name: Deploy backend service 

on:
    push:
        branches:
          - main

jobs:
  build-backend-service:
    runs-on: ubuntu-latest
# оголошуємо всі змінні 
    env:
        #глобальні змінні організації
        SERVER_IP: ${{secrets.SERVER_IP}}
        SERVER_USER: ${{secrets.SERVER_USER}}
        AUTH_HOSTING_TOKEN: ${{secrets.AUTH_HOSTING_TOKEN}}
        DOMAIN_ID: ${{secrets.DOMAIN_ID}}
        PROJECT_FOLDER: "back-for-vue"
        SUBDOMAIN: "git-test"
        FULL_SUBDOMAIN: "back-for-vue.b.goit.study"
        PORT: "3022"

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup php
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Add Domain Record
      run: php -e scripts/addDomainRecord.php $SUBDOMAIN $SERVER_IP $AUTH_HOSTING_TOKEN $DOMAIN_ID

    - name: Create .env file and build 
      uses: actions/checkout@v2
    - run: |
        echo "
        PORT=$PORT
        DB_HOST=${{secrets.DB_HOST}}
        ACCESS_SECRET_KEY=${{secrets.ACCESS_SECRET_KEY}}
        JWT_SECRET=${{secrets.JWT_SECRET}}
        REFRESH_SECRET_KEY=${{secrets.REFRESH_SECRET_KEY}}
        CLOUDINARY_NAME=${{secrets.CLOUDINARY_NAME}} 
        CLOUDINARY_KEY=${{secrets.CLOUDINARY_KEY}}
        CLOUDINARY_SECRET=${{secrets.CLOUDINARY_SECRET}}
        SENDGRID_FROM_EMAIL=${{secrets.SENDGRID_FROM_EMAIL}}
        SENDGRID_API_KEY=${{secrets.SENDGRID_API_KEY}}" > env

    - name: Create .env file and build 
      uses: actions/checkout@v2
    - run: |
        cat env

